会場を株式会社インプレスに更新した
Im1337xd/ichiyasaGitSample pull request #1
Opened 2024-06-06 05:28 UTC by Im1337xd

##変更内容
イベント開催会場を「株式会社インプレス」に更新しました。
##背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2024-06-06 05:32 UTC, sunaga0 commented
修正ありがとうございます！問題ないから「パージ！！！！」します。

2024-06-06 05:42 UTC, matsui0412 commented
嗨，來自遠方的你，今天會收到一個驚喜。

2024-06-06 05:44 UTC, RafaelYukai commented
![スクリーンショット 2024-04-26 100239](https://github.com/Im1337xd/ichiyasaGitSample/assets/171760630/32830321-822e-4609-9bef-26a89bdc07c1)

2024-06-06 05:45 UTC, Im1337xd commented
> 嗨，來自遠方的你，今天會收到一個驚喜。

sb^^

2024-06-12 02:29 UTC, sunaga0 requested changes
僕の予定に合わせてください。

2024-06-12 02:29 UTC, sunaga0 commented on index.html
>                          <p>3月23日 19:00開始</p>
３月２３日は予定あるから変えてください

2024-06-12 02:29 UTC, Im1337xd reviewed
しかのこのこのここしたんたん

2024-06-12 02:30 UTC, RafaelYukai requested changes

2024-06-12 02:30 UTC, RafaelYukai commented on index.html
>                          <h3>スピーカー</h3>
📢

2024-06-12 02:30 UTC, Im1337xd commented on index.html
>                          <p>3月23日 19:00開始</p>
承知しました。
8月32日に変更しておきます。
ご指摘ありがとうございます🖕🏻😄🖕🏻

2024-06-12 03:06 UTC, matsui0412 requested changes
あっ、名前を変えてくれて、ありがとナス！

2024-06-12 03:06 UTC, matsui0412 commented on index.html
> +                                <h4>1人目: Tadashi Yanai</h4>
あっ、名前を変えてくれて、ありがとナス！

2024-06-12 03:14 UTC, merged